### ISSUE TITLE
Issue deleting

### ISSUE THREAD

**Issue by jacksoncharles** [jyu213/ssh2-sftp-client#19]
I'm unable to delete a file using the following code where I copy files to S3 then try an delete the original but I keep getting a file not found error detailed below. I am not the strongest JS developer and apologise if I have made a simple mistake.

return sftpClient.get( source )
  .then((data) => {
    data.on('data', (chunk) => {

	S3.putObject({
	  Bucket: CONFIG.DESTINATION_BUCKET,
	  Key: fileName,
	  Body: chunk
	}, function( err, data ) {
 	  if( err === null ) {
		sftpClient.delete( source ).then(( data ) => {
		  if( err !== null ) {
		      console.log('=== Ooops, we have an error ===');
		      console.log( err );
		  }
	})
	.catch( function(e) {
	  console.log('=== we have caught an error deleting and the error is ===');
	console.log(e);
    });
} 
})...

The error reads

2017-05-26T14:16:15.797Z	de4db9bf-421d-11e7-88ce-ffa94f8fa45b	{ Error: File not found
at SFTPStream._transform (/var/task/node_modules/ssh2-sftp-client/node_modules/ssh2-streams/lib/sftp.js:384:27)
at SFTPStream.Transform._read (_stream_transform.js:167:10)
at SFTPStream._read (/var/task/node_modules/ssh2-sftp-client/node_modules/ssh2-streams/lib/sftp.js:170:15)
at SFTPStream.Transform._write (_stream_transform.js:155:12)
at doWrite (_stream_writable.js:334:12)
at writeOrBuffer (_stream_writable.js:320:5)
at SFTPStream.Writable.write (_stream_writable.js:247:11)
at Channel.ondata (_stream_readable.js:555:20)
at emitOne (events.js:96:13)
at Channel.emit (events.js:188:7) code: 2, lang: 'en' }

**Comment by jacksoncharles** [comment]
Apologies, I got working with this syntax

    return sftpClient.connect( configuration )
	.then(() =>
		sftpClient.delete( source );
	        }).then(() => {
	            return sftp.end();
	        })							
		.catch( function(e) {
			console.log(e);
		});
