### ISSUE TITLE
Error: Unable to start subsystem: sftp

### ISSUE THREAD

**Issue by hxl-dy** [jyu213/ssh2-sftp-client#84]
on windows 10, using node v6
```
Error: Unable to start subsystem: sftp
    at D:\workspace\mine\nodejs\node_modules\ssh2-sftp-client\node_modules\ssh2\lib\client.js:1418:19
    at SSH2Stream.<anonymous> (D:\workspace\mine\nodejs\node_modules\ssh2-sftp-client\node_modules\ssh2\lib\Channel.js:205:24)
    at emitNone (events.js:86:13)
    at SSH2Stream.emit (events.js:185:7)
    at parsePacket (D:\workspace\mine\nodejs\node_modules\ssh2-sftp-client\node_modules\ssh2-streams\lib\ssh.js:3509:10)
    at SSH2Stream._transform (D:\workspace\mine\nodejs\node_modules\ssh2-sftp-client\node_modules\ssh2-streams\lib\ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (D:\workspace\mine\nodejs\node_modules\ssh2-sftp-client\node_modules\ssh2-streams\lib\ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:333:12) 'catch error'
```

**Comment by jyu213** [comment]
search [this](https://github.com/mscdex/ssh2/issues/406) for help

**Comment by hxl-dy** [comment]
this issue is nothing to do with this repo
